-- schema.sql

-- URLs Table
CREATE TABLE IF NOT EXISTS public.urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code TEXT UNIQUE NOT NULL,
    long_url TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Analytics Table
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id BIGINT REFERENCES public.urls(id) ON DELETE CASCADE,
    visitor_country TEXT,
    user_agent TEXT,
    ip_address TEXT,
    referer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_urls_short_code ON public.urls (short_code);
CREATE INDEX IF NOT EXISTS idx_urls_user_id ON public.urls (user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_url_id ON public.analytics (url_id);
CREATE INDEX IF NOT EXISTS idx_analytics_created_at ON public.analytics (created_at);

-- Set up Row Level Security (RLS)
ALTER TABLE public.urls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- URLs Policies
-- 1. Anyone can read URLs (needed for redirect worker unless using service role)
CREATE POLICY "Urls are readable by everyone" ON public.urls FOR SELECT USING (true);

-- 2. Authenticated users can insert their own URLs
CREATE POLICY "Users can insert their own urls" ON public.urls FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. Authenticated users can update/delete their own URLs
CREATE POLICY "Users can update their own urls" ON public.urls FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own urls" ON public.urls FOR DELETE USING (auth.uid() = user_id);

-- Analytics Policies
-- 1. Analytics are insertable by everyone (Cloudflare Worker needs to insert)
-- Important: For production, you might want to restrict this to a specific worker service key, 
-- but public anon key access is often easiest for Workers to just use Supabase HTTP API.
CREATE POLICY "Analytics can be inserted by anyone" ON public.analytics FOR INSERT WITH CHECK (true);

-- 2. Users can only select analytics for their own URLs
CREATE POLICY "Users can read analytics of their urls" ON public.analytics FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.urls
        WHERE public.urls.id = analytics.url_id
        AND public.urls.user_id = auth.uid()
    )
);
